# Tools/email_tools.py

def fetch_latest_statement_email() -> dict:
    """
    Simulated email inbox tool.

    This does NOT connect to a real email inbox.
    For the capstone, it pretends to find the latest bank statement email
    and returns metadata plus the path to the attached CSV generated by Agent 0.

    Returns:
        dict with keys:
          - status: "success" or "error"
          - subject: email subject line
          - from_address: sender email
          - bank_name: detected bank name
          - statement_type: e.g. 'savings_account'
          - attachment_path: relative path to the statement file
    """
    # This must match the filename in your project root.
    attachment_path = "Agent 0 Output Manually Enriched Simulated Bank Statement_v2.csv"

    return {
        "status": "success",
        "subject": "Your April 2015 bank statement is ready",
        "from_address": "alerts@samplebank.com",
        "bank_name": "SampleBank",
        "statement_type": "savings_account",
        "attachment_path": attachment_path,
    }
